# Generated by Django 2.0 on 2017-12-17 20:31

from django.db import migrations
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_rando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrandomizationlist',
            name='drug_assignment',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, choices=[('single_dose', 'Single-dose: Ambisome 10mg/kg on day 1 with Flucytosine 100mg/kg/day and Fluconazole 1200mg/day for 14 days.'), ('control', 'Control: Amphotericin B 1 mg/kg for 7 days with Flucytosine 100mg/kg/day for 7 days followed by Fluconazole 1200mg/day for 7 days.')], help_text=' (Encryption: RSA local)', max_length=71),
        ),
        migrations.AlterField(
            model_name='randomizationlist',
            name='drug_assignment',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, choices=[('single_dose', 'Single-dose: Ambisome 10mg/kg on day 1 with Flucytosine 100mg/kg/day and Fluconazole 1200mg/day for 14 days.'), ('control', 'Control: Amphotericin B 1 mg/kg for 7 days with Flucytosine 100mg/kg/day for 7 days followed by Fluconazole 1200mg/day for 7 days.')], help_text=' (Encryption: RSA local)', max_length=71),
        ),
    ]
