# Generated by Django 2.0 on 2017-12-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_rando', '0002_auto_20171211_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectConsent',
        ),
    ]
